### ISSUE TITLE
;|

### ISSUE THREAD

**Issue by xrevix** [Rdimo/Discord-Webhook-Protector#4] opened 2022-05-18 11:50 UTC
![image](https://user-images.githubusercontent.com/85802406/169031346-0f626a4d-2935-4a78-b4d8-5543bb8a51f4.png)

**Comment by Rdimo** [comment] 2022-05-18 14:04
want to vc in my [discord](https://cheataway.com/invite) and try to help me fix it?

**Comment by Rdimo** [comment] 2022-05-18 14:05
ah wait, lmao mb mb I know what the issue is hold on

**Comment by Rdimo** [comment] 2022-05-18 14:46
@xrevix try and see if it works now

**Comment by xrevix** [comment] 2022-05-18 16:43
![image](https://user-images.githubusercontent.com/85802406/169096918-0ff2b961-5492-4220-8830-7e1cec2f86b2.png)
@Rdimo :(

**Comment by Rdimo** [comment] 2022-05-18 16:48
> ![image](https://user-images.githubusercontent.com/85802406/169096918-0ff2b961-5492-4220-8830-7e1cec2f86b2.png) @Rdimo :(

you need to install the modules

**Comment by xrevix** [comment] 2022-05-18 16:49
i do

**Comment by Rdimo** [comment] 2022-05-18 16:54
ah, ye I just forgot to add it to the package

**Comment by Rdimo** [comment] 2022-05-18 16:59
tysm for reporting all these bugs btw 💀 let me credit you

**Comment by xrevix** [comment] 2022-05-18 17:06
Thx<3
![image](https://user-images.githubusercontent.com/85802406/169101207-d0dc9448-c401-4798-acbe-699612b1daaa.png)
lol

**Comment by Rdimo** [comment] 2022-05-18 17:15
bro what is wrong with heroku

**Comment by xrevix** [comment] 2022-05-18 17:17
lolll🤣

**Comment by Rdimo** [comment] 2022-05-22 13:27
> lolll🤣

ight this is fixed now

**Closed by Rdimo** 2022-05-22 13:27 UTC
